on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci --prefer-offline --no-audit
      - run: npm run check:format
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm ci --prefer-offline --no-audit
      - run: npm run test:unit
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: cypress-io/github-action@v5
        with:
          start: npm run dev
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: cypress/videos
          retention-days: 1
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: cypress/screenshots
          retention-days: 1
